site_name: Portfolio de Jordan Flament
theme:
  name: material
  logo: images/france.webp
  favicon: images/france.webp
  features:
    - navigation.top
    - toc.integrate
    - navigation.expand
  palette:
    # Mode sombre
    scheme : slate
    primary : indigo
    accent : blue

extra_javascript:
  - javascripts/effet.js

nav:
  - 🏠 Accueil: index.md
  - 🚀 Mes Projets:
      - 🤖 Ligne d'embouteillage: projetYacco.md
      - ⚡ Retrofit Safety Stacker: projetKingspan.md

extra:
  analytics:
    provider: google
    property: G-06NNT8QSN9