site_name: Portfolio de Jordan Flament
theme:
  name: material
  logo: images/france.webp
  favicon: images/france.webp
  features:
    - navigation.top
    - toc.integrate
    - navigation.expand
  palette:
    # Mode clair
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: slate
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre
    
    # Mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: slate
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer en mode clair

extra_javascript:
  - javascripts/effet.js

nav:
  - Menu: index.md