site_name: Portfolio de Jordan Flament
theme:
  logo: images/france.webp
  favicon: images/france.webp
  name: material
  palette:
    # Mode clair
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: slate
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre
    
    # Mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: slate
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer en mode clair

nav:
  - Accueil: index.md
  - Mon Parcours: parcours.md
  - Mes Projets: projets.md

extra_javascript:
  - javascripts/effet.js